-- Backfill `recipe`.`method` for Recipes imported from a URL.
--
-- Generated by scripts/backfill-recipe-method.mjs on 2026-08-06
-- against http://localhost:8080/.netlify/functions/recipes
-- by re-reading each Recipe's own remote_url through the app's URL Import path
-- and keeping only the method. Resolves follow-ups.md #41 for the Recipes that
-- have a source to re-read. Counts, and every skip with its reason, are at the
-- foot of this file.
--
-- Safe to apply more than once, and safe to apply to a database that has moved
-- on since this was generated. Every statement below:
--
--   * writes `method` and nothing else. Ingredients, name and tags are never
--     touched, so a page that re-read thinly cannot damage good data - #41's
--     worst case;
--   * requires `remote_url` still to match the page the method was read from,
--     so a Recipe whose id has shifted is a no-op rather than a wrong write;
--   * requires `method` still to be empty, so a method written by hand since
--     this file was generated is never overwritten.
--
-- Deliberately not wrapped in a transaction: each statement is independent and
-- self-guarding, so a partially written or partially applied file is still
-- correct. Re-run the generator to pick up whatever is still missing.
--
-- Pure DML. Unlike 027 this file is not endangered by `mysql --force`, since
-- every statement stands alone - a skipped one costs one method and nothing
-- else. It is applied that way locally, in fact: docker/mysql-init runs every
-- migrations/*.sql with --force, and this one matches no rows there at all
-- because migrations run against an empty database. Against production, apply
-- it without --force, so that a failure is visible rather than skipped.

-- Method text is full of degree signs, accents and dashes, and a mysql client
-- whose default character set is latin1 will read these UTF-8 bytes as latin1
-- and store them double-encoded - "180°C" arriving as "180Â°C" - without
-- erroring. Declaring the encoding here rather than relying on how the file
-- happens to be piped in is what stops that.
SET NAMES utf8mb4;

-- 1  Shepherds Pie
--     https://www.thecoast.net.nz/life/food-recipes/gordon-ramsay-s-shepherds-pie/
UPDATE `recipe` SET `method` = '1. Preheat the oven to 180°C.
2. Heat the oil in a large pan until hot. Season the lamb mince and fry over moderate-high heat for 2.5 minutes.
3. Stir in the onion and carrot, then grate in the garlic. Add the Worcestershire sauce, tomato puree, thyme and rosemary, and cook for 1.5 minutes, stirring constantly.
4. Pour in the red wine and reduce until almost completely evaporated. Add the chicken stock, bring to the boil, then simmer until the sauce has thickened.
5. Meanwhile, cook the potatoes in boiling salted water until tender. Drain, then return them to the hot pan over low heat briefly to dry out.
6. Pass the potatoes through a potato ricer, then beat in the egg yolks followed by the grated parmesan. Check the seasoning.
7. Spoon the lamb mixture into the base of a large ovenproof dish. Layer the mashed potato generously over the top, starting at the outside and working towards the middle.
8. Grate extra parmesan over the top and season. Fluff the mash with a fork to create rough peaks.
9. Bake for approximately 19 minutes, until bubbling and golden brown.'
WHERE `id` = 1
  AND `remote_url` = 'https://www.thecoast.net.nz/life/food-recipes/gordon-ramsay-s-shepherds-pie/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 10  Spaghetti and Meatballs
--     https://natashaskitchen.com/spaghetti-and-meatballs-recipe/
UPDATE `recipe` SET `method` = '1. Combine the bread with the water and leave for 5 minutes, then mash with a fork.
2. In a large bowl, combine the beef mince, sausage, grated parmesan, 4 cloves garlic, egg, and mashed bread mixture. Mix until well combined.
3. Form the mixture into meatballs about 4 cm wide. Roll lightly in flour and shake off any excess.
4. Heat oil in a deep large skillet or Dutch oven over medium heat. Brown the meatballs in 2 batches, turning until browned on all sides, about 6 minutes total. Remove and set aside.
5. In the same skillet, sauté the onion over medium heat until soft and golden, about 5 minutes. Add the remaining 4 cloves garlic and cook for 1 to 2 minutes.
6. Stir in the crushed tomato and bay leaves. Bring to a light boil.
7. Return the meatballs to the sauce, partially cover, and simmer gently for 30 minutes, turning occasionally. Stir in the basil a few minutes before the sauce is done, then season to taste.
8. Meanwhile, cook the spaghetti in boiling water according to the packet instructions until al dente. Drain and return to the pot.
9. Pour the sauce and meatballs over the spaghetti and toss gently. Garnish with extra parmesan and basil if desired, then serve hot.'
WHERE `id` = 10
  AND `remote_url` = 'https://natashaskitchen.com/spaghetti-and-meatballs-recipe/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 13  Pea and Cauliflower Curry
--     https://sheerluxe.com/recipes/pea-and-cauliflower-curry
UPDATE `recipe` SET `method` = '1. Crush the green chillies and ginger with a pinch of salt using a pestle and mortar or blender, until they form a fine masala paste.
2. Heat the oil in a large, thick-based frying pan over a medium heat for 30 seconds, then add the cumin seeds and mustard seeds.
3. When the mustard seeds begin to pop, reduce the heat to low and stir in the asafetida.
4. Stir in the cauliflower, return the heat to medium, then add the masala paste, turmeric, ground coriander, salt, sugar and boiling water, if using fresh peas.
5. Cover and cook for 8-10 minutes, stirring every few minutes.
6. Stir in the peas and tomato, cover again and cook for a further 3-5 minutes.
7. Remove from the heat, sprinkle over the coriander, cover again and leave to rest for 5 minutes.
8. Serve.'
WHERE `id` = 13
  AND `remote_url` = 'https://sheerluxe.com/recipes/pea-and-cauliflower-curry'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 15  Chicken, Leek & Mushroom Pie
--     https://www.bbc.co.uk/food/recipes/chickenandmushroompi_89034
UPDATE `recipe` SET `method` = '1. Preheat the oven to 200C, 180C fan, or gas 6.
2. Heat the oil in a frying pan. Add the chicken and fry until it begins to turn white.
3. Add the mushrooms and continue frying until the chicken is golden-brown.
4. Remove the chicken and mushrooms from the pan and set aside. Add the onion and garlic to the same pan and fry for 2.5 minutes, or until softened. Remove from the heat and set aside with the chicken and mushrooms.
5. Melt the butter in a saucepan. Stir in the flour and cook for about 3 minutes, stirring constantly, until it forms a thick, smooth paste.
6. Mix the milk and stock in a jug, then add the nutmeg, white pepper and salt to taste. Slowly pour the liquid into the flour mixture, whisking constantly until smooth. Simmer over a gentle heat, stirring constantly, for about 5 minutes or until smooth and thickened.
7. Stir in the parsley and pour the sauce over the chicken and mushroom mixture. Mix well, then spoon into a pie dish and leave until completely cool.
8. If using a block of pastry, roll it out on a lightly floured surface until it is the thickness of a pound coin. Brush the edges of the pie dish with beaten egg, lay the pastry on top, press down the edges and trim. Brush the top with beaten egg and use leftover pastry to decorate if desired.
9. Make two or three slits in the top to allow steam to escape. Bake for 22.5 minutes, or until the pastry is golden-brown.'
WHERE `id` = 15
  AND `remote_url` = 'https://www.bbc.co.uk/food/recipes/chickenandmushroompi_89034'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 20  Nicoise Salad
--     https://www.bbc.co.uk/food/recipes/saladenicoise_6572
UPDATE `recipe` SET `method` = '1. Whisk together the red wine vinegar, olive oil, parsley, chives, garlic, salt and pepper to make the dressing or marinade.
2. Place the tuna in a shallow dish and pour over half the dressing. Cover and chill for 1.5 hours, tossing in the marinade occasionally.
3. Heat a ridged griddle pan or barbecue for 5 minutes. Remove the tuna from the marinade and cook for 2.5 minutes on each side, depending on how rare you prefer it.
4. Arrange the lettuce on a large plate. Add the onion, tomatoes, potato, tuna, green beans and anchovies. Drizzle with the remaining dressing, then add the eggs, olives and basil.'
WHERE `id` = 20
  AND `remote_url` = 'https://www.bbc.co.uk/food/recipes/saladenicoise_6572'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 21  Prawn & Chorizo Paella
--     https://www.foxandbriar.com/shrimp-chorizo-paella/
UPDATE `recipe` SET `method` = '1. Heat a large paella or sauté pan over medium heat. Add the olive oil. Once hot, add the onion and sauté for 5 minutes, until softened and golden. Add the garlic and sauté for 30 seconds.
2. Add the tomato paste and cook for 2.5 minutes, until fully incorporated and the onion is rust-coloured.
3. Add the salt, smoked paprika, chilli flakes, turmeric and saffron. Stir to combine.
4. Add the rice and stir-fry until completely coated with the oil and spices.
5. Stir in the chicken stock and bring to a simmer.
6. Reduce the heat to low and simmer for 10 minutes.
7. Add the sliced chorizo and cook for about 5 minutes more.
8. Arrange the prawns on top, pressing them into the rice so they are almost covered by the remaining liquid. Cook for 7.5 minutes more, or until the liquid has evaporated.
9. Sprinkle with parsley and serve.'
WHERE `id` = 21
  AND `remote_url` = 'https://www.foxandbriar.com/shrimp-chorizo-paella/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 24  Sticky Garlic Chicken Bites
--     https://tasty.co/recipe/sticky-garlic-chicken-bites
UPDATE `recipe` SET `method` = '1. Preheat the oven to 200°C.
2. Cut the chicken breasts into small bite-size pieces.
3. Dip the chicken pieces into the beaten egg, then coat with panko breadcrumbs.
4. Place the breaded chicken on a baking sheet and season with salt and pepper.
5. Bake for 20 minutes, until golden brown and cooked through.
6. Combine the soy sauce, honey, garlic, hoisin sauce, sriracha sauce, and ginger in a saucepan. Bring to a boil, then remove from the heat.
7. Toss the chicken bites in the sauce until thoroughly coated.
8. Serve immediately, garnished with spring onion and sesame seeds.'
WHERE `id` = 24
  AND `remote_url` = 'https://tasty.co/recipe/sticky-garlic-chicken-bites'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 25  Lamb Kofta and Salad
--     https://www.recipetineats.com/lamb-koftas-yoghurt-dressing-2/
UPDATE `recipe` SET `method` = '1. Combine the yoghurt, olive oil, garlic, cumin, lemon juice, salt and pepper for the yoghurt sauce. Refrigerate for at least 20 minutes, or overnight.
2. Grate the onion into a large bowl. Add the lamb mince, breadcrumbs, garlic, coriander, spices, salt and pepper. Mix thoroughly with your hands.
3. With damp hands, divide the mixture into 8 equal portions. Press and shape each portion around a skewer.
4. Cook the koftas using one of the following methods:
   - Stove: Heat oil in a large skillet over medium-high heat. Cook in batches for 5 minutes total, turning until evenly browned.
   - BBQ: Cook over medium-high heat for about 6 minutes, rotating until browned all over.
   - Oven grill: Preheat the grill. Cook the koftas 30 cm from the heat source for 12 minutes, rotating as needed until lightly browned.
5. Serve the koftas with warmed flatbreads and yoghurt sauce. Add shredded red cabbage, carrot and mint salad, or shredded lettuce, tomato and onion, if desired.'
WHERE `id` = 25
  AND `remote_url` = 'https://www.recipetineats.com/lamb-koftas-yoghurt-dressing-2/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 26  Butter Chicken
--     http://maunikagowardhan.co.uk/cook-in-a-curry/tandoori-chicken-tikka-barbecue-chicken-cooked-in-a-chilli-garlic-marinade/,  https://maunikagowardhan.co.uk/cook-in-a-curry/butter-chicken-murgh-makhani-chicken-cooked-in-a-spiced-tomato-gravy/
UPDATE `recipe` SET `method` = '1. Prepare tandoori chicken according to a separate tandoori chicken recipe. Set the cooked chicken aside.
2. Heat a heavy-bottomed saucepan and add the butter. Add the green cardamom, cinnamon stick and cloves; fry for 20 seconds.
3. Add the onion and sauté over medium heat for 5–7 minutes, until lightly browned.
4. Add the ginger and green chillies. Fry for 1 minute.
5. Add the Kashmiri chilli powder, garam masala and tomato puree. Stir well and cook for a couple of minutes.
6. Gradually add the double cream, stirring continuously until the spices are fully combined. Simmer for 2–3 minutes.
7. Add a splash of water if the curry is too thick. Stir in the honey and kasuri methi, then season to taste.
8. Add the cooked chicken pieces and simmer over low heat for 8–10 minutes.
9. Garnish with coriander and serve with roti or paratha.'
WHERE `id` = 26
  AND `remote_url` = 'http://maunikagowardhan.co.uk/cook-in-a-curry/tandoori-chicken-tikka-barbecue-chicken-cooked-in-a-chilli-garlic-marinade/,  https://maunikagowardhan.co.uk/cook-in-a-curry/butter-chicken-murgh-makhani-chicken-cooked-in-a-spiced-tomato-gravy/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 33  Apple Crumble
--     https://www.bbcgoodfood.com/recipes/vegan-apple-crumble
UPDATE `recipe` SET `method` = '1. Heat the oven to 190C/170C fan/gas 5. Toss the apples with the golden caster sugar and put them in a 23cm round baking dish at least 5cm deep, or a 20cm square dish. Flatten with your hand.
2. For the crumble topping, mix the flour and sugar in a bowl with a good pinch of salt. Rub in the dairy-free spread with your fingertips until the mixture looks like moist breadcrumbs. Shake the bowl and rub in any large pieces that come to the surface.
3. Pour the crumble mixture over the apples, then use a fork to spread it evenly. Gently press the surface with the back of the fork so the crumble holds together and becomes crisp. Drag the fork lightly over the top for a decorative finish. Sprinkle the oats and demerara sugar evenly over the top.
4. Place on a baking tray and bake for 35-40 minutes, until the top is golden and the apples are very soft when pierced with a small sharp knife. Leave to cool for 10 minutes before serving with oat-based vegan cream or custard.'
WHERE `id` = 33
  AND `remote_url` = 'https://www.bbcgoodfood.com/recipes/vegan-apple-crumble'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 36  Chicken Tacos
--     https://carlsbadcravings.com/easy-slow-cooker-shredded-mexican-chicken-recipe/
UPDATE `recipe` SET `method` = '1. Rub the chicken breasts with oil and place in the bottom of a slow cooker. Add all remaining ingredients except the hot sauce.
2. Cook on high for 2-4 hours, or on low for 6-7 hours, until the chicken is tender enough to shred.
3. Shred the chicken and cook on low for a further 20 minutes to absorb some of the liquid.
4. Drain any excess liquid, taste, and add hot sauce as desired.'
WHERE `id` = 36
  AND `remote_url` = 'https://carlsbadcravings.com/easy-slow-cooker-shredded-mexican-chicken-recipe/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 41  Mushroom Soup
--     https://www.bbcgoodfood.com/recipes/mushroom-soup
UPDATE `recipe` SET `method` = '1. Heat the butter in a large saucepan and cook the onions and garlic until soft but not browned, about 9 minutes.
2. Add the mushrooms and cook over a high heat for another 3 minutes, until softened. Sprinkle over the flour and stir to combine. Pour in the chicken stock, bring to the boil, then add the bay leaf and simmer for 10 minutes.
3. Remove and discard the bay leaf. Remove the mushroom mixture from the heat and blitz with a hand blender until smooth.
4. Gently reheat the soup and stir through the cream. Scatter over the parsley, if using, and serve.'
WHERE `id` = 41
  AND `remote_url` = 'https://www.bbcgoodfood.com/recipes/mushroom-soup'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 43  Chicken Fricassee
--     https://goodyfoodies.blogspot.com/2014/08/recipe-chicken-fricassee-gordon-ramsay.html
UPDATE `recipe` SET `method` = '1. Heat a large heavy-based sauté pan or casserole over medium heat. Season the chicken, then sauté for 3-4 minutes on one side until golden, cooking in batches if necessary.
2. Turn the chicken over. Add the bacon, garlic, and mushrooms, and mix well. Stir in the bay leaf, rosemary, and thyme.
3. Add the brandy. Increase the heat to medium-high and simmer for 1 minute, then reduce to medium and simmer gently for 2-3 minutes.
4. Pour in the chicken stock and bring to a gentle simmer. Cook uncovered over medium-low heat for 10 minutes, then cover and cook for a further 15 minutes, until the chicken is cooked through.
5. Optional: transfer the chicken to a baking tray and grill on high for 4-5 minutes to crisp the skin.
6. Increase the heat under the pan to medium-high and reduce the sauce until slightly thickened.
7. Discard the garlic, rosemary, and bay leaf. Serve the chicken topped with the mushroom and bacon sauce. Garnish with thyme or parsley, if desired.'
WHERE `id` = 43
  AND `remote_url` = 'https://goodyfoodies.blogspot.com/2014/08/recipe-chicken-fricassee-gordon-ramsay.html'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 44  Fresh Egg Pasta
--     https://www.saltfatacidheat.com/fat/pasta-alluovo
UPDATE `recipe` SET `method` = '1. Mound the flour in the centre of a large, wide mixing bowl. Make a well in the centre and add the eggs and egg yolks. Using a fork, beat the eggs and gradually incorporate the flour from the inner rim of the well. Continue until about half the flour is incorporated and the dough forms a shaggy mass.
2. Use your fingers to mix the dough, pressing any loose flour into the dough. If needed, add another egg yolk or a tablespoon of water to absorb all the flour. Once cohesive, remove the dough from the bowl.
3. Transfer the dough to a lightly floured surface and knead for 4 to 5 minutes, until smooth, elastic and uniform in colour. Wrap in plastic and rest at room temperature for at least 30 minutes and up to 4 hours.
4. Line three baking sheets with parchment paper and lightly dust with semolina flour.
5. Cut off one quarter of the dough, rewrap the remainder and set it aside. Flatten the piece into an oval about the width of the pasta machine. Set the rollers to their widest setting and pass the dough through.
6. Lay the dough on a lightly floured work surface and fold it in half so it is again the width of the pasta machine. Pass it through the widest setting again. Continue folding the dough in thirds and rolling it until smooth, silky and even-textured, keeping the sheet as wide as the machine.
7. Roll the dough once through each of the next 2 to 3 settings, dusting with flour as needed, until it is about 1/4 inch thick.
8. From this point, roll the dough twice through each setting. Lightly dust both sides with flour as needed to prevent sticking. Continue until the pasta is thin enough to see the outline of your hand beneath it, about 1/16 inch thick for noodles.
9. Cut the pasta into sheets 12 to 14 inches long. Lightly dust with semolina flour, stack on a prepared baking sheet and cover with a clean, lightly damp kitchen towel. Repeat with the remaining dough.
10. For roller-cut noodles, pass each pasta sheet through the cutting attachment, then toss with semolina flour. Gently fluff and separate the noodles, form into single-portion nests, and place on the prepared baking sheets. Cover until ready to use.
11. For hand-cut noodles, stack four semolina-dusted pasta sheets and loosely fold them in thirds lengthwise. Cut with a sharp knife:
    - Cut in 1/2-inch increments for tagliatelle or fettuccine.
    - Cut in 3/4-inch increments for pappardelle.
12. Gently fluff and separate the noodles, form into single-portion nests on the prepared baking sheets, and cover until ready to use.'
WHERE `id` = 44
  AND `remote_url` = 'https://www.saltfatacidheat.com/fat/pasta-alluovo'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 45  Pasta with Prawns and Spinach
--     https://tasty.co/recipe/one-pot-lemon-garlic-shrimp-pasta
UPDATE `recipe` SET `method` = '1. Bring a large pot of water to the boil. Add the linguine and cook, stirring frequently, until al dente.
2. Drain the pasta and set aside.
3. In the same pot, heat the olive oil with 2 tablespoons of the butter. Add the garlic and chilli flakes, then cook until fragrant.
4. Add the prawns, salt, and pepper. Stir until the prawns begin to turn pink but are not fully cooked.
5. Add the oregano and spinach, then cook until the spinach has wilted.
6. Return the cooked linguine to the pot. Add the remaining butter, parmesan, and parsley, stirring until well combined and the butter has melted.
7. Once the prawns are cooked through, add the lemon juice, stir again, and serve hot.'
WHERE `id` = 45
  AND `remote_url` = 'https://tasty.co/recipe/one-pot-lemon-garlic-shrimp-pasta'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 49  Bagels
--     https://www.sophisticatedgourmet.com/2009/10/new-york-style-bagel-recipe/
UPDATE `recipe` SET `method` = '1. Pour the sugar and yeast into 120 millilitres of the warm water without stirring. Leave for 5 minutes, then stir until dissolved.
2. Mix the flour and salt in a large bowl. Make a well in the centre and add the yeast mixture.
3. Add 80 millilitres of warm water, then mix in the remaining water as needed to make a moist, firm dough. Add up to 60 millilitres more water if necessary.
4. Knead the dough on a floured work surface for about 10 minutes, until smooth and elastic. Work in as much flour as needed to make a firm, stiff dough.
5. Lightly oil a large bowl, add the dough and turn to coat. Cover with a damp towel and leave in a warm place for 1 hour, until doubled in size. Punch down the dough and rest for 10 minutes.
6. Divide the dough into 8 pieces. Shape each piece into a smooth round.
7. Press a floured finger through the centre of each dough ball to make a ring. Stretch each ring to form a bagel and place on a lightly oiled baking sheet.
8. Cover the shaped bagels with a damp towel and rest for 10 minutes. Meanwhile, preheat the oven to 220°C.
9. Bring a large pot of water to the boil, then reduce the heat. Lower in the bagels in batches. Once they float, boil for 1 minute, flip, and boil for 1 more minute. For chewier bagels, boil for 2 minutes on each side.
10. Add optional toppings as the bagels come out of the water. An egg wash may be used to help toppings stick.
11. Transfer the boiled bagels to an oiled or parchment-lined baking sheet.
12. Bake for 20 to 25 minutes, until golden brown.
13. Cool on a wire rack before serving.'
WHERE `id` = 49
  AND `remote_url` = 'https://www.sophisticatedgourmet.com/2009/10/new-york-style-bagel-recipe/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 50  Pizzas
--     https://anitalianinmykitchen.com/best-pizza-dough/
UPDATE `recipe` SET `method` = '1. Add the lukewarm water to the bowl of a stand mixer or a large bowl. Sprinkle over the sugar and yeast, leave for 5-10 minutes, then stir to combine.
2. For machine kneading, add the olive oil, flour and salt. Mix with the dough hook on low speed, scrape down the hook, then knead on medium speed for 5-7 minutes, scraping the hook halfway through, until the dough is smooth and elastic.
3. For hand kneading, add the olive oil, flour and salt and mix with a fork until the dough begins to come together. Turn out onto a lightly floured surface and knead for about 10 minutes, until smooth and elastic. Add a little extra flour if the dough is very sticky.
4. Place the dough in a lightly oiled bowl and turn it to coat. Cover with plastic wrap and a clean kitchen towel, then leave in a warm, draft-free place for about 2 hours, or until doubled in size.
5. Preheat the oven to 250°C. Punch down the dough, divide into 1-3 balls and leave to rest for 20 minutes.
6. Place the dough on lightly oiled pizza trays or baking sheets and shape it with clean hands.
7. Add your preferred toppings and bake for 15-20 minutes, until the crust is golden and the cheese has melted.
8. Alternatively, refrigerate the dough in an airtight plastic bag for up to 24 hours.
9. For a simple tomato sauce, combine a tin of diced or puréed tomatoes with oregano, basil, salt and olive oil, then spread over the pizza dough.
10. For a fresh tomato topping, chop grape, cherry or Roma tomatoes. Remove the seeds from Roma tomatoes, then toss with oregano, basil, salt and olive oil.
11. For a sausage topping, fry chopped Italian sausage until beginning to brown. Add sliced onion, pepper, mushrooms, olive oil, oregano, basil, salt and pepper, then cook over medium heat for about 10 minutes. Use as a pizza topping over the sauce before baking.'
WHERE `id` = 50
  AND `remote_url` = 'https://anitalianinmykitchen.com/best-pizza-dough/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 51  Roast Chicken
--     https://www.epicurious.com/recipes/food/views/my-favorite-simple-roast-chicken-231348
UPDATE `recipe` SET `method` = '1. Preheat the oven to 450°F. Rinse the chicken and pat it dry inside and out with paper towels.
2. Season the cavity with salt and black pepper, then truss the chicken with kitchen string.
3. Season the outside of the chicken generously with salt and black pepper.
4. Place the chicken breast-side up in a sauté pan or roasting pan. Roast until an instant-read thermometer in the thickest part of the breast reads 150–155°F, about 50–60 minutes.
5. Add the thyme to the pan, if using. Baste the chicken with the pan juices and thyme, then transfer it to a cutting board and rest for 15 minutes.
6. Remove the kitchen string, carve the chicken, and serve on the bone with unsalted butter.'
WHERE `id` = 51
  AND `remote_url` = 'https://www.epicurious.com/recipes/food/views/my-favorite-simple-roast-chicken-231348'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 55  Duck breast with cabbage, beetroot and sweet potato
--     https://www.greatbritishchefs.com/recipes/duck-breast-recipe-lavender-beetroot-sweet-potato
UPDATE `recipe` SET `method` = '1. Toast the szechuan pepper, coriander seeds, cumin seeds and fennel seeds in a dry pan over medium heat for 5 minutes.
2. Roughly crush the toasted spices using a mortar and pestle. Mix with the lavender and set aside.
3. Preheat the oven to 190°C, gas mark 5. Cover the beetroot with foil and roast until tender, about 37.5 minutes. Allow to cool slightly, peel while still warm, then cut into large cubes.
4. Dice the sweet potato, season with salt and coat with olive oil. Place on a baking tray and roast until tender, about 40 minutes, alongside the beetroot.
5. Heat a large dry pan over medium-high heat. Season the duck breasts with salt and place them skin-side down in the pan. Slowly render the fat, carefully spooning off excess fat as it is released.
6. Cook the duck for 6 minutes, then turn and cook for a further 4 minutes. Finish in the oven at 220°C, gas mark 6, for 2 minutes. Rest for 6 minutes.
7. Press the flesh side of the rested duck breasts into the spice and lavender mixture.
8. Heat a second pan over medium-high heat. Add butter and, once foaming, add the roasted beetroot and sweet potato. Heat through, season with salt, then remove from the heat.
9. Return the duck to the pan, flesh-side down, and sear the spices for 1 minute. Add the maple syrup and coat the duck until reduced to a sticky glaze. Slice and serve over the roasted vegetables.'
WHERE `id` = 55
  AND `remote_url` = 'https://www.greatbritishchefs.com/recipes/duck-breast-recipe-lavender-beetroot-sweet-potato'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 56  Dairy Free Strawberry Tart
--     https://www.bbcgoodfood.com/recipes/strawberry-tart
UPDATE `recipe` SET `method` = '1. Beat the unsalted butter and icing sugar together until smooth but not fluffy. Mix in the egg until combined, then add the flour. Bring together with your hands to form a dough. Wrap and chill in the fridge for 30 minutes.
2. Dust a surface with flour and roll out the pastry to a 26cm circle, or 3cm bigger than your tin. Line a 23cm fluted tart tin with the pastry, leaving an overhang. Prick the base with a fork to stop air bubbles forming. Chill for 30 minutes.
3. Heat the oven to 200C, 180C fan, or gas 6. Line the pastry case with a scrunched-up sheet of baking parchment and baking beans, then bake for 15 minutes. Remove the parchment and beans and bake for another 15-20 minutes until crisp and golden. Leave in the tin to cool.
4. Make the crème pâtissière:
   - Heat the milk, double cream and vanilla extract in a pan over a medium heat, stirring occasionally. Bring to a simmer.
   - Meanwhile, whisk the egg yolks and caster sugar in a bowl for 3 minutes until pale, then stir in the cornflour until combined.
   - Pour a quarter of the hot cream over the egg mixture, whisking continuously. Pour the warm egg mixture into the pan with the remaining cream.
   - Stir over a low-medium heat for 5-8 minutes until thickened. Transfer to a large bowl and cool for 15 minutes, whisking occasionally.
   - Gradually whisk in the butter until smooth, cover and refrigerate until needed.
5. Beat the strawberry jam to loosen it, then spread it over the bottom of the pastry case. Put the crème pâtissière into a piping bag and pipe in a spiral on top of the jam. Arrange the strawberries on top in a pattern.
6. Heat the apricot jam in a small pan with 1 tablespoon water until warm. Whisk to loosen, then leave to cool slightly. Brush over the strawberries.'
WHERE `id` = 56
  AND `remote_url` = 'https://www.bbcgoodfood.com/recipes/strawberry-tart'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 57  Teriyaki Chicken
--     https://www.bbcgoodfood.com/recipes/easy-teriyaki-chicken
UPDATE `recipe` SET `method` = '1. Heat the sesame oil in a non-stick pan over a medium heat. Add the chicken and fry for 7 minutes, or until golden.
2. Add the garlic and ginger and fry for 2 minutes.
3. Stir in the honey, soy sauce, rice wine vinegar and 100 millilitres water. Bring to the boil and cook for 2–5 minutes over a medium heat, until the chicken is sticky and coated in a thick sauce.
4. Scatter over the spring onion and sesame seeds. Serve with sticky rice and steamed bok choi or spring greens.'
WHERE `id` = 57
  AND `remote_url` = 'https://www.bbcgoodfood.com/recipes/easy-teriyaki-chicken'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 64  Surowka
--     https://www.kwestiasmaku.com/przepis/surowka-z-mlodej-kapusty
UPDATE `recipe` SET `method` = '1. Wash and dry the cabbage, finely shred it, and place it in a large bowl.
2. Add the finely diced spring onion, peeled and grated carrot, and chopped dill.
3. Pour in the oil or olive oil and lemon juice. Season with salt and pepper, then mix well.'
WHERE `id` = 64
  AND `remote_url` = 'https://www.kwestiasmaku.com/przepis/surowka-z-mlodej-kapusty'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 66  Gigantes with tomatoes and greens
--     https://www.bbc.co.uk/food/recipes/gigantes_with_tomatoes_47546/amp
UPDATE `recipe` SET `method` = '1. Drain the beans, cover with fresh water and bring to the boil. Reduce to a simmer and cook for 1.75 hours, until the beans are just tender.
2. Gently soften the onion and garlic in 2 tablespoons of the olive oil for 5 minutes. Stir in the sweet paprika, tomato puree, chopped tomatoes, water, salt and pepper.
3. Bring to the boil, then reduce to a simmer and cook for 30 minutes. Stir in the chard and remove from the heat.
4. Preheat the oven to 160C, 140C fan, or gas mark 3.
5. Drain the cooked beans and mix with the tomato and chard sauce. Add a further 2 tablespoons of olive oil and the chopped herbs.
6. Transfer to a casserole pan, drizzle with the remaining olive oil, and bake for 37.5 minutes until tender, thickened and bubbling. Serve hot, warm, or at room temperature.'
WHERE `id` = 66
  AND `remote_url` = 'https://www.bbc.co.uk/food/recipes/gigantes_with_tomatoes_47546/amp'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 67  Satay Sweet Potato Curry
--     https://www.bbcgoodfood.com/recipes/satay-sweet-potato-curry
UPDATE `recipe` SET `method` = '1. Melt the coconut oil in a saucepan over medium heat. Add the onion and soften for 5 minutes.
2. Add the garlic and ginger, then cook for 1 minute until fragrant.
3. Stir in the thai red curry paste, peanut butter, and sweet potato. Add the coconut milk and water.
4. Bring to the boil, reduce the heat, and simmer uncovered for 25-30 minutes, or until the sweet potato is soft.
5. Stir through the spinach and lime juice. Season well.
6. Serve with cooked rice and sprinkle with dry roasted peanuts, if desired.'
WHERE `id` = 67
  AND `remote_url` = 'https://www.bbcgoodfood.com/recipes/satay-sweet-potato-curry'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 68  Thai Red Curry
--     https://www.recipetineats.com/thai-red-curry-with-chicken/
UPDATE `recipe` SET `method` = '1. Heat oil in a large heavy-based skillet over medium-high heat.
2. Add the red curry paste and, if using jarred paste, the garlic, ginger and lemongrass paste. Cook for about 2 minutes until the paste dries out.
3. Add the chicken stock and stir to dissolve the paste. Simmer rapidly for 3 minutes, or until the liquid has reduced by half.
4. Add the coconut milk, kaffir lime leaves and fish sauce. Stir, then add the chicken.
5. Spread the chicken out and bring to a simmer. Reduce the heat to medium and simmer for 8 to 10 minutes, until the chicken is cooked and the sauce has reduced to the desired thickness.
6. Taste and adjust the seasoning with additional fish sauce for saltiness or sugar for sweetness, if desired.
7. Add the pumpkin and green beans. Stir and cook for about 3 minutes, until the pumpkin is just cooked through and the sauce has thickened.
8. Remove from the heat and stir through the thai basil leaves.
9. Serve over jasmine rice, garnished with red chilli and coriander cilantro leaves, if desired.'
WHERE `id` = 68
  AND `remote_url` = 'https://www.recipetineats.com/thai-red-curry-with-chicken/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 83  Lamb Salli Boti
--     http://www.athomewithfj.com/Lamb-Sali-Boti.html
UPDATE `recipe` SET `method` = '1. Heat the oil in a large karahi, wok or sturdy casserole.
2. Add the bay leaves and cinnamon, stir for a few seconds, then add the red onion.
3. Cook over a medium-high heat, stirring often, until the onions are golden.
4. Add the garlic and ginger, then fry over a medium heat for 2.5 minutes.
5. Stir in the chilli powder, turmeric and garam masala. Fry for 1 minute, then add the chopped tomatoes.
6. Cook for 4.5 minutes, until the tomatoes thicken and the oil starts to separate from the masala.
7. Add the lamb and fry over a medium-high heat until well browned, about 20 minutes. Add a little water if the spices start catching on the bottom of the pan.
8. Pour in enough water to cover the meat, cover with a lid, and simmer until tender, about 45 minutes.
9. Alternatively, cook the curry in an oven at 170C or gas mark 3 for about 45 minutes.
10. Stir in the white wine vinegar and jaggery or date palm sugar.
11. Just before serving, scatter over the potato matchstick straws and coriander. Serve with lemon wedges on the side.'
WHERE `id` = 83
  AND `remote_url` = 'http://www.athomewithfj.com/Lamb-Sali-Boti.html'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 89  Porchetta w/ Salsa Verde
--     https://basicswithbabish.co/basicsepisodes/porchetta
UPDATE `recipe` SET `method` = '1. Remove the skin from the portion of pork belly that will be inside the roll.
2. Score the meat inside the belly in both directions, making cuts about 5 cm apart and 2.5 cm deep to create a crosshatch pattern.
3. Trim the pork belly into a neat rectangle.
4. Season the meat with nutmeg, orange zest, sage, rosemary, fennel fronds or fennel seeds, pine nuts, chilli flakes, and crushed garlic. Press the seasonings into the scored cuts.
5. Roll the pork belly tightly. Make shallow lateral cuts through the skin, ensuring they do not reach the fat.
6. Tie the roast with butcher''s twine every 2.5 to 7.5 cm.
7. Place the roast on a wire rack over a baking sheet and refrigerate uncovered overnight.
8. Line the baking sheet with foil, return the rack and roast to the tray, and heat the oven to 250°F. Insert a temperature probe into the thickest part of the roast.
9. Roast for 3 to 8 hours, until the internal temperature reaches 160°F.
10. Remove the roast carefully, as there will be a large amount of rendered fat.
11. Increase the oven temperature to 500°F. Return the roast to the oven and watch closely until the skin is crisp without burning.
12. Rest for 30 minutes before slicing.
13. To make the salsa verde, combine parsley, lemon zest and juice, capers, white wine vinegar, anchovies, garlic, olive oil, and chilli flakes in a food processor or immersion blender bowl. Blend until chopped but still textured.
14. Season the salsa verde to taste with salt and pepper.
15. For sandwiches, layer thinly sliced porchetta on focaccia, spread with salsa verde, top with arugula, then secure with skewers, slice, and serve.'
WHERE `id` = 89
  AND `remote_url` = 'https://basicswithbabish.co/basicsepisodes/porchetta'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 94  Spicy Sausage Rice
--     https://www.aglugofoil.com/2012/10/spicy-sausage-rice-recipe-gordon-ramsay.html
UPDATE `recipe` SET `method` = '1. Heat the olive oil in a heavy-based casserole dish. Fry the onion for 5 minutes, until soft but not coloured.
2. Add the red pepper and garlic. Cook for 2 minutes, stirring so the garlic does not burn.
3. Cut open the sausage casings and break up the meat into small, meatball-sized pieces.
4. Turn the heat to high and cook the sausage, stirring, for about 4-5 minutes until nicely browned.
5. Stir in the smoked paprika, then add the rice and mix well to combine and coat it in the flavour.
6. Deglaze the pan with the white wine, scraping up any bits stuck to the bottom.
7. Add the chicken stock and bring to a boil, then reduce to a simmer. Do not cover.
8. Cook gently for 15-20 minutes, until the rice is tender and the liquid is almost fully absorbed. Stir from time to time.
9. Taste and adjust the seasoning as needed. Gently stir in the spring onion and tomato, then cook for 1 more minute.
10. Sprinkle with the flat-leaf parsley and serve immediately.'
WHERE `id` = 94
  AND `remote_url` = 'https://www.aglugofoil.com/2012/10/spicy-sausage-rice-recipe-gordon-ramsay.html'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 99  Golabki
--     https://aniagotuje.pl/przepis/golabki-bez-zawijania
UPDATE `recipe` SET `method` = '1. Finely shred the cabbage, mix with salt, and leave for 10–20 minutes. Squeeze out the released liquid thoroughly.
2. Grind the pork shoulder. Cook the rice, drain it, and allow it to cool slightly.
3. Heat 3 tablespoons of oil in a pan. Finely chop the onion and fry over a medium heat for about 10 minutes, until golden.
4. Combine the ground pork, squeezed cabbage, cooked rice, fried onion, egg, chopped dill, salt, and pepper. Knead for at least 5 minutes until evenly mixed.
5. Shape the mixture into about 21 flattened patties.
6. Heat the remaining oil in a large frying pan. Fry the patties in batches over a medium-high heat for about 1 minute per side, until browned.
7. Pour the stock into a large pot. Stir in the passata and tomato paste, then bring to a boil.
8. Add all the browned patties to the sauce. Reduce the heat so the sauce gently simmers and cook uncovered for 35 minutes.
9. Taste the sauce and season if needed. Serve hot.'
WHERE `id` = 99
  AND `remote_url` = 'https://aniagotuje.pl/przepis/golabki-bez-zawijania'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 100  Kale, Pea and Walnut Pesto Pasta
--     https://www.waitrose.com/ecom/recipe/wholewheat-pasta-with-kale-pea-and-walnut-pesto
UPDATE `recipe` SET `method` = '1. Put the peas in a large heatproof bowl and cover with just-boiled water. Drain and rinse under cold water.
2. Blanch the kale in boiling water for 1 minute. Drain, rinse under cold water, then wring dry in a clean tea towel.
3. Transfer the kale to a food processor with the drained peas, basil and a pinch of salt. Blend until roughly chopped.
4. Add the walnuts, garlic and parmesan, then blend again. With the motor running, drizzle in the olive oil. Season to taste.
5. Cook the spaghetti for 2 minutes less than the packet instructions. Reserve a large ladleful of the cooking water, then drain.
6. Add a little reserved pasta water to the pesto and blend until combined.
7. Toss the pesto and chilli flakes through the pasta. Add lemon juice and more reserved pasta water as needed to create a loose, silky texture.
8. Serve with extra grated parmesan and chilli flakes, if liked.'
WHERE `id` = 100
  AND `remote_url` = 'https://www.waitrose.com/ecom/recipe/wholewheat-pasta-with-kale-pea-and-walnut-pesto'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 101  Chermoula Meatballs
--     https://www.waitrose.com/ecom/recipe/chermoula-meatballs
UPDATE `recipe` SET `method` = '1. Heat the oil in a large, high-sided nonstick frying pan. Cook the meatballs over a medium-high heat for 7 minutes, turning regularly, until browned on all sides.
2. Meanwhile, slice the red onion and peppers. Transfer the browned meatballs to a plate with a slotted spoon. Discard excess fat from the pan, leaving about 1 tablespoon.
3. Reduce the heat to medium. Add the onion and peppers and fry for 5 minutes, stirring occasionally, until softened.
4. Stir in the chermoula paste and cook for 2 minutes, stirring.
5. Add the chopped tomatoes, return the meatballs to the pan and season. Simmer for 10 minutes, stirring occasionally, until the sauce has thickened slightly and the meatballs are cooked through with no pink meat.
6. Meanwhile, microwave the cauliflower, kale and couscous pouches for 4.5 minutes, or until piping hot. Leave to stand for 1 minute.
7. Chop most of the mint and stir it through the meatballs. Scatter over the remaining mint leaves and serve with the couscous.'
WHERE `id` = 101
  AND `remote_url` = 'https://www.waitrose.com/ecom/recipe/chermoula-meatballs'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 106  Okra Fries
--     https://foodism.co.uk/recipes/make-dishoom-okra-fries/
UPDATE `recipe` SET `method` = '1. Wash the okra under cold water and pat completely dry with kitchen paper. Remove and discard the top of each okra, leaving the tail intact. Slice small okra in half lengthways; quarter large okra lengthways.
2. Mix the garlic paste, ginger paste, deggi mirch and water. Add the okra and mix well to coat.
3. Heat the vegetable oil in a deep-fryer or deep, heavy-based pan to 180°C.
4. Mix the chickpea flour and cornflour. Sprinkle over the okra and toss very gently to coat.
5. Fry the okra in batches if necessary until golden and crispy, about 4.5 minutes. Drain on kitchen paper, sprinkle with magic masala and serve immediately with chutney.'
WHERE `id` = 106
  AND `remote_url` = 'https://foodism.co.uk/recipes/make-dishoom-okra-fries/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 107  Oven Baked Ribs
--     https://homeisakitchen.com/2013/07/18/dry-rubbed-fall-off-the-bone-beef-ribs-in-the-oven/
UPDATE `recipe` SET `method` = '1. Optional: remove the silverskin from the underside of the ribs. Use a sharp knife to lift a flap of connective tissue, then pull it away with your hands or a paper towel. Avoid damaging the meat.
2. Put the onion powder, garlic powder, brown sugar, cumin, salt, chilli powder, and smoked paprika in a bowl.
3. Add the oil and mix well to form a crumbly paste.
4. Apply the spice mixture generously to both sides of the beef ribs, using all of the mixture.
5. Put the ribs in an airtight container or zip-top bag. Marinate at room temperature for 1 to 2 hours for same-day cooking, or refrigerate overnight.
6. Preheat the oven to 250°F to 265°F.
7. Line a large baking sheet with foil and arrange the ribs on it in a single layer. Seal them in a foil pouch.
8. Bake on the middle rack for 3 to 4 hours, until the ribs are very tender.
9. Open the foil pouch and set the oven to high broil. Broil the ribs on the middle rack for about 5 minutes, watching closely to prevent the rendered fat from catching fire.
10. Brush the ribs lightly with bbq sauce, if desired. Cut apart a whole rack before serving, then serve immediately.'
WHERE `id` = 107
  AND `remote_url` = 'https://homeisakitchen.com/2013/07/18/dry-rubbed-fall-off-the-bone-beef-ribs-in-the-oven/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 109  Chorizo and Tomato Rice
--     https://www.waitrose.com/ecom/recipe/tomato-rice-with-chorizo-smoked-paprika
UPDATE `recipe` SET `method` = '1. Heat the oil in a large frying pan or casserole pan over a medium-low heat with the garlic, bay leaves, coriander seeds and chilli. Sauté for 1 minute, or until the seeds start to skip around.
2. Add the leek and salt, then cook, stirring, for 2 minutes until the leek is just starting to soften. Move the leek to the sides of the pan.
3. Add the chorizo and cook for 4 minutes, stirring occasionally, until the red oil starts to come out. Stir in the tomatoes and cook for 5 minutes until they start to fall apart.
4. Boil a kettle. Add the tomato puree, smoked paprika and rice to the tomato mixture and mix well to coat.
5. Pour over the just-boiled water, reduce the heat to low, cover and simmer for 16 minutes.
6. Turn off the heat and keep covered for another 15 minutes to rest and steam. Serve sprinkled with parsley.'
WHERE `id` = 109
  AND `remote_url` = 'https://www.waitrose.com/ecom/recipe/tomato-rice-with-chorizo-smoked-paprika'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 112  Thai Green Curry
--     https://hot-thai-kitchen.com/green-curry-new-2/#tasty-recipes-6636-jump-target
UPDATE `recipe` SET `method` = '1. Optional: pound the thai basil leaves and fingerroot in a mortar and pestle until smooth. Add the shrimp paste and green curry paste, then pound until combined. Alternatively, blend these with some chicken stock until smooth.
2. Bring about 0.75 cup of the coconut milk to a full boil in a heavy-bottomed pot over medium heat. Add the curry paste and sauté, stirring frequently, for 3-5 minutes, until coconut oil separates from the paste. If it does not separate, continue with the recipe.
3. Add the chicken thigh and stir to coat with the curry paste.
4. Add the remaining coconut milk, chicken stock, fish sauce and palm sugar. Twist and tear the kaffir lime leaves, discarding the centre stems, then add them to the pot. Bring to a gentle simmer and cook for 10-15 minutes, until the chicken is fork-tender.
5. Meanwhile, cut the thai eggplant into bite-sized pieces and keep submerged in water until needed.
6. Add the thai eggplant to the curry. Push it beneath the surface for the first minute, then cook for a further 2 minutes, until just tender with slight resistance when pierced. If using bamboo shoots instead, heat them through for about 1 minute.
7. Turn off the heat. Stir in the red pepper, allowing it to soften in the residual heat, then stir in the thai basil leaves.
8. Taste and adjust with more fish sauce if needed. Serve with jasmine rice.
9. If using chicken breast instead, marinate it in 1 tablespoon fish sauce while preparing the curry. Add it after the eggplant has cooked for 1 minute, then cook for about 2 minutes, until just done.'
WHERE `id` = 112
  AND `remote_url` = 'https://hot-thai-kitchen.com/green-curry-new-2/#tasty-recipes-6636-jump-target'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 114  Braised Short Rib
--     https://basicswithbabish.co/basicsepisodes/short-ribs
UPDATE `recipe` SET `method` = '1. Trim excess silver skin and fat from the short ribs.
2. Season the ribs generously with salt and black pepper.
3. Peel and chop the carrots, slice the onions, and chop the celery into large chunks.
4. Heat the vegetable oil in a large Dutch oven over medium-high heat until smoking.
5. Brown the ribs in batches on all sides, without overcrowding the pot. Return each rib to the same spot to avoid burning the fond. If the fond is exposed, add onions to protect it from burning.
6. Remove the browned ribs and set aside. Add the onions and sauté until soft and browned, about 5-7 minutes. Add the tomato paste and sauté for 2-3 minutes, until slightly darkened.
7. Add the carrots and celery and sauté briefly to warm through.
8. Add the garlic, ale or wine, chicken or beef stock, soy sauce, and prune juice. Stir to combine, then add the thyme and parsley sprigs.
9. Nestle the ribs back into the pot with their least-browned sides facing up. The liquid should cover most of the ribs while leaving their tops slightly exposed.
10. Preheat the oven to 135°C. Cover the pot and braise for 4-5 hours, checking after 3.5 hours. The ribs are ready when easily pierced with a paring knife.
11. Remove the ribs and strain the braising liquid. Skim away excess fat if serving immediately. If making ahead, cool the liquid quickly with ice cubes, chill for at least 4 hours, then remove the solidified fat.
12. Return the ribs to the reduced sauce and reheat for 20 minutes. Baste with sauce, cover, and allow the ribs to rest briefly to absorb the flavours.
13. Serve over mashed potatoes or polenta, topped with the reduced sauce and fresh parsley.'
WHERE `id` = 114
  AND `remote_url` = 'https://basicswithbabish.co/basicsepisodes/short-ribs'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 90116  Barley & mushroom risotto
--     https://www.bbcgoodfood.com/recipes/barley-chicken-mushroom-risotto
UPDATE `recipe` SET `method` = '1. Heat the butter and oil in a large heavy saucepan. Sauté the shallots and garlic with seasoning for 5 minutes, then stir in the chicken and cook for 2 minutes.
2. Add the barley and cook for 1 minute. Pour in the wine and stir until absorbed.
3. Add the mushrooms and thyme, then pour over three-quarters of the stock. Simmer gently for 40 minutes, stirring occasionally and topping up with the remaining stock if needed, until the barley is tender.
4. Remove from the heat and stir in the grated parmesan. Serve immediately, topped with chives and parmesan shavings if desired.'
WHERE `id` = 90116
  AND `remote_url` = 'https://www.bbcgoodfood.com/recipes/barley-chicken-mushroom-risotto'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 90117  Fluffy Waffles
--     https://natashaskitchen.com/fluffy-waffle-recipe/
UPDATE `recipe` SET `method` = '1. In a large mixing bowl, beat the eggs and sugar with an electric hand mixer or stand mixer fitted with a whisk attachment on high speed for 3 minutes, until fluffy.
2. Add the oil, milk, and vanilla extract.
3. Stir the baking powder and salt into the flour, then add the dry ingredients to the bowl.
4. Beat on low speed just until combined. Do not overmix; the batter should have small lumps.
5. Preheat the waffle iron. Grease it if needed.
6. Add enough batter to barely fill the grooves, leaving space for expansion. Cover and cook until golden and crisp, or until the timer is done. Remove the waffle with plastic or silicone tongs and serve warm.'
WHERE `id` = 90117
  AND `remote_url` = 'https://natashaskitchen.com/fluffy-waffle-recipe/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 150116  Cauliflower, pomegranate and pistachio salad
--     https://ottolenghi.co.uk/pages/recipes/cauliflower-pomegranate-pistachio-salad
UPDATE `recipe` SET `method` = '1. Preheat the oven to 200°C fan.
2. Coarsely grate one-third of the cauliflower and set aside in a bowl.
3. Break the remaining cauliflower into florets about 3 cm wide. Add to a separate bowl with any cauliflower leaves and the onion.
4. Toss with 2 tablespoons of oil and ¼ teaspoon of salt. Spread on a large parchment-lined baking tray and roast for about 20 minutes, until cooked through and golden brown. Set aside to cool.
5. Put the cooled roasted vegetables in a large bowl with 50 ml oil, the grated cauliflower, and the remaining ingredients, plus ¼ teaspoon of salt.
6. Toss gently to combine, transfer to a platter, and serve.'
WHERE `id` = 150116
  AND `remote_url` = 'https://ottolenghi.co.uk/pages/recipes/cauliflower-pomegranate-pistachio-salad'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 240120  Pilau Rice
--     https://www.bbcgoodfood.com/recipes/easy-pilau-rice
UPDATE `recipe` SET `method` = '1. Soak the rice in cold water for 30 minutes, if time allows. Rinse under cold running water, drain, and repeat until the water is only slightly cloudy. Leave to drain completely in a sieve.
2. Heat the butter in a lidded pan over medium heat. Gently fry the onion with a large pinch of salt for 10 minutes, stirring occasionally, until soft and golden.
3. Stir in the cinnamon, cumin seeds, cardamom, cloves and bay leaves, and cook for 2 minutes. Add the ground coriander and turmeric, then cook for 1 minute.
4. Gently stir in the drained rice to coat in the onion mixture. Pour over the vegetable stock and stir well.
5. Cover and turn the heat up. Once hot, uncover, stir the rice, cover again and reduce the heat to low. Cook for 2 minutes, then turn off the heat and leave covered for 10 minutes.
6. Uncover and stir well, then cover again and leave for 5 minutes. Fluff with a fork before serving.'
WHERE `id` = 240120
  AND `remote_url` = 'https://www.bbcgoodfood.com/recipes/easy-pilau-rice'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 270116  Chicken Pad See Ew
--     https://simplehomeedit.com/recipe/pad-see-ew/
UPDATE `recipe` SET `method` = '1. Add the chicken, tamari sauce, and sesame oil to a medium bowl. Toss to coat.
2. Bring a medium pot of water to the boil. Add the rice noodles and cook until just softened and pliable, about 2.5 minutes. Rinse and drain immediately under cold tap water. The noodles may still be firm in places; they will finish cooking in the pan.
3. Heat the olive oil in a large, deep, heavy-based frying pan over high heat. Add the garlic and cook, stirring, for 30 seconds until fragrant.
4. Add the chicken and cook for about 2.5 minutes, until it has just changed colour. Push it to one side of the pan.
5. Add the eggs and cook for 2 minutes, breaking them up as they cook, until firm.
6. Add the Chinese broccoli and cook for 1 minute, until just softened.
7. Add the tamari sauce, dark soy sauce, fish sauce, and brown sugar. Cook, stirring, for 1 minute or until the sauce has slightly thickened and caramelised.
8. Toss through the cooked noodles.
9. Combine the bird''s eye chilli and rice wine vinegar, if using. Drizzle over the noodles to serve.'
WHERE `id` = 270116
  AND `remote_url` = 'https://simplehomeedit.com/recipe/pad-see-ew/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 300116  Chicken Korma
--     https://simplehomeedit.com/recipe/chicken-korma/
UPDATE `recipe` SET `method` = '1. Heat the ghee, coconut oil, or olive oil in a large heavy-based frying pan over medium-high heat. Add the onion and fresh ginger, then cook for 2.5 minutes until soft and fragrant.
2. Add the korma paste and cook, stirring, for 30 seconds.
3. Add the chicken and cook for 3.5 minutes, until sealed.
4. Add the coconut cream and sugar, then simmer for 8 minutes.
5. Top with yoghurt and coriander, if using. Serve with steamed basmati rice, pappadums, and pineapple and coriander salsa.'
WHERE `id` = 300116
  AND `remote_url` = 'https://simplehomeedit.com/recipe/chicken-korma/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 300117  Slow-cooked Beef Stroganoff
--     https://simplehomeedit.com/recipe/slow-cooked-beef-stroganoff/
UPDATE `recipe` SET `method` = '1. Season the beef with salt and pepper.
2. Heat 1 tablespoon olive oil in a large, deep, heavy-based pan over medium-high heat. Brown the beef in batches for 2-3 minutes on each side, adding the remaining oil as needed. Set aside.
3. Add 60 millilitres water to the pan and scrape up the browned bits. When most of the water has evaporated, add the onion and garlic and cook, stirring, for 2-3 minutes until softened.
4. Add the mushrooms and cook for 2-3 minutes until softened.
5. Add the flour and stir continuously for 30 seconds, until a paste forms around the onion and mushrooms.
6. Choose a cooking method:
   - Slow cooker: Add the tomato paste, paprika, Worcestershire sauce and beef stock to the slow cooker. Add the beef and mushroom mixture, then cook on high for 4 hours or low for 8 hours.
   - Pressure cooker: Add the tomato paste, paprika, Worcestershire sauce and beef stock to the pressure cooker insert. Return the beef and mushroom mixture, secure the lid, and cook on high pressure for 35 minutes. Let pressure release naturally for 10 minutes, then release any remaining pressure.
   - Stovetop: Add the tomato paste, paprika, Worcestershire sauce and beef stock to the pan, then return the beef. Bring to the boil, cover, and simmer over the lowest heat for 1.5 hours, stirring occasionally. Remove the lid and cook for 1 additional hour to thicken.
7. Check that the beef pulls apart easily with a fork. Continue cooking in short intervals if needed until tender.
8. Ladle about 250 millilitres sauce into a small bowl. Mix in the sour cream, then return the mixture to the cooker or pan and stir to combine.
9. If desired, reduce the sauce uncovered for 5-10 minutes, stirring occasionally, until thickened. Add up to 125 millilitres water if the stovetop sauce is sticking.
10. Serve with pasta, rice, polenta or mashed potato, garnished with parsley if using.'
WHERE `id` = 300117
  AND `remote_url` = 'https://simplehomeedit.com/recipe/slow-cooked-beef-stroganoff/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 300118  Slow-cooked Massaman Beef Curry
--     https://simplehomeedit.com/recipe/massaman-beef-slow-cooker/
UPDATE `recipe` SET `method` = '1. Heat the oil in a large heavy-based frying pan over medium heat. Brown the beef for 3–4 minutes per side, then set aside.
2. In a medium bowl, stir together the curry paste, chicken stock and coconut milk to make a sauce.
3. Add the fish sauce, sugar and lime juice, if using, and mix well.
4. Layer the beef, potato and onion in the slow-cooker, in that order.
5. Pour over the sauce. The potato and onion do not need to be fully submerged.
6. Add the cinnamon sticks and star anise, if using.
7. Cook on high for 4 hours or low for 8 hours. If the beef is still firm, continue cooking on high in 30-minute intervals until it falls apart easily. Pull the beef into bite-sized pieces with tongs or forks.
8. Alternatively, cook in a pressure cooker on high pressure for 1 hour, then quick-release the pressure. If needed, simmer with the lid off for 5–10 minutes to thicken the sauce.
9. Serve over steamed jasmine rice with roti or naan. Top with peanuts, coriander, chilli and lime wedges.'
WHERE `id` = 300118
  AND `remote_url` = 'https://simplehomeedit.com/recipe/massaman-beef-slow-cooker/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 300119  Wonton Dumpling Soup
--     https://simplehomeedit.com/recipe/wonton-dumpling-soup/
UPDATE `recipe` SET `method` = '1. Add the pork mince, Shaoxing wine, tamari sauce, ginger, spring onion and salt to a large bowl. Combine with your hands.
2. Lay 5–8 gow gee wrappers at a time on a flat surface. Place 1 heaped teaspoon of filling on one half of each wrapper. Brush the outer edge with water, fold in half to enclose the filling, and press to seal.
3. Place the prepared wontons on a plate and cover with a damp tea towel while working to prevent them drying out.
4. Add the chicken stock, Shaoxing wine and sesame oil to a large pot. Bring to the boil over high heat.
5. Add the dumplings and cook for 4 minutes, or until they rise to the surface. Remove with a slotted spoon and divide between serving bowls with some broth.
6. Add the noodles to the pot and cook for 1 minute, until just pliable. Add the Chinese broccoli stalks and cook for 1 minute, or until the noodles are cooked through. Add the leaves and cook for a further 30 seconds, until just wilted.
7. Serve the wontons with additional broth. Drizzle with chilli oil, extra tamari sauce, sesame oil and spring onion, if desired.'
WHERE `id` = 300119
  AND `remote_url` = 'https://simplehomeedit.com/recipe/wonton-dumpling-soup/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 300120  Creamy Sausage Pasta
--     https://simplehomeedit.com/recipe/creamy-sausage-pasta/
UPDATE `recipe` SET `method` = '1. Bring a large pot of salted water to the boil.
2. If using fresh lasagne sheets, cut or tear them into strips about 2.5 cm thick. Cook them after preparing the sauce for 30–60 seconds, then drain and add directly to the sauce.
3. If using regular pasta, cook it according to the packet instructions, reducing the cooking time by 1 minute. Drain well.
4. Heat the olive oil in a large pan over medium heat.
5. Add the sausages and cook for about 5 minutes, breaking them into small pieces, until browned and cooked through.
6. Add the garlic and cook for 30 seconds until fragrant.
7. Stir in the tomato paste and cook for 1–2 minutes to caramelise.
8. Add the white wine and simmer for 2–3 minutes, scraping the bottom of the pan to deglaze.
9. When most of the wine has evaporated, add the chicken stock. Cook for 2–3 minutes, until reduced by half.
10. Stir in the Italian mixed herbs and crushed chillies, if using.
11. Add the cream, stir well, and simmer for 3–4 minutes until slightly thickened.
12. Stir in the grated parmesan and season with salt and pepper. Turn off the heat, add the cooked pasta, and stir through the sauce.
13. Serve immediately with extra parmesan, if desired.'
WHERE `id` = 300120
  AND `remote_url` = 'https://simplehomeedit.com/recipe/creamy-sausage-pasta/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 330116  Slow-cooker Beef Stew
--     https://simplehomeedit.com/recipe/slow-cooker-beef-stew/
UPDATE `recipe` SET `method` = '1. Place the beef in a large, shallow dish. Season with salt and pepper, add the flour, and toss with tongs until evenly coated.
2. Heat half the olive oil in a large heavy-based frying pan over medium-high heat. Brown the beef in batches for 2-3 minutes per batch, adding more oil as needed and avoiding overcrowding. Set aside.
3. Add 60 ml water to the pan and scrape up the browned bits from the base.
4. Add the onion and garlic and cook, stirring, for 1-2 minutes.
5. Transfer the beef, onion, and garlic to the slow cooker.
6. Add the carrot, tomato paste, Worcestershire sauce, beef stock, thyme, and bay leaves. Stir to combine. Cook on high for 3-4 hours or on low for 7-8 hours, until the beef and carrots are tender.
7. During the final 15 minutes, stir in the peas and cornflour mixed with cold water. Remove and discard the bay leaves and any thyme sprigs. Leave the lid off for the final 15 minutes to thicken slightly.
8. Season to taste with salt and pepper. Serve with mashed potatoes and a sprinkle of fresh thyme leaves, if desired.'
WHERE `id` = 330116
  AND `remote_url` = 'https://simplehomeedit.com/recipe/slow-cooker-beef-stew/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 330117  Slow-cooked Beef Ragu
--     https://simplehomeedit.com/recipe/slow-cooked-beef-ragu/
UPDATE `recipe` SET `method` = '1. Heat the olive oil in a deep heavy-based pan with a lid over medium-high heat.
2. Add the onion, carrot, celery and garlic. Cook, stirring, for 4 minutes until softened.
3. Turn the heat to high, add the chuck steak and cook, stirring, for 2.5 minutes until the meat is sealed all over.
4. Add the red wine, tomato paste, passata, beef stock, salt, pepper, thyme and bay leaves. Stir to combine and bring to a gentle simmer.
5. Cover, reduce the heat to the lowest setting, and cook for 2.5 hours or until the beef is tender enough to be easily shredded with two forks.
6. Shred the beef with two forks and serve with pasta and grated parmesan.'
WHERE `id` = 330117
  AND `remote_url` = 'https://simplehomeedit.com/recipe/slow-cooked-beef-ragu/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 330118  Easy Roasted Garlic Butter Chicken
--     https://simplehomeedit.com/recipe/roasted-garlic-butter-chicken/
UPDATE `recipe` SET `method` = '1. Preheat the oven to 200°C, or 180°C fan-forced.
2. Combine the butter, salt, black pepper, garlic, honey and thyme in a small bowl to make the marinade.
3. Arrange the chicken thighs skin-side up on a sided baking tray.
4. Spread the butter mixture all over the chicken, focusing mainly on the skin. Pour the chicken stock around the chicken.
5. Roast for 57.5 minutes, basting once halfway through, until golden and cooked through.
6. Serve with mashed potatoes and steamed asparagus or greens, drizzle with tray juices, and garnish with extra thyme and black pepper.
7. Alternatively, for the air fryer, combine the butter, salt, pepper, garlic, honey and thyme in a small bowl.
8. Pat the chicken thighs dry with paper towel.
9. Spread the butter mixture generously over the chicken thighs, focusing on the skin.
10. Preheat the air fryer to 190°C for about 5 minutes. Lightly grease the basket or tray.
11. Arrange the chicken skin-side up in a single layer, cooking in batches if needed. Air fry for 27.5 minutes, flipping halfway through, until golden, crispy and cooked through. Baste with melted butter from the basket halfway through if desired.
12. Rest the chicken for 5 minutes before serving.'
WHERE `id` = 330118
  AND `remote_url` = 'https://simplehomeedit.com/recipe/roasted-garlic-butter-chicken/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 330119  Juicy Beef Rissoles
--     https://simplehomeedit.com/recipe/beef-rissoles/
UPDATE `recipe` SET `method` = '1. Add the beef mince, onion, garlic, egg, panko breadcrumbs, ketchup, Worcestershire sauce, pepper, salt or stock powder to a large mixing bowl. Combine with your hands.
2. Roll the mixture into golf-ball-sized portions, then flatten each portion with your palm to form rissoles.
3. For stovetop cooking, heat olive oil in a large heavy-based frying pan over medium-low heat.
4. Cook the rissoles for 8-10 minutes, turning once halfway through, until browned and cooked through. Cook in batches if needed so the pan is not crowded.
5. Set the cooked rissoles aside on a plate.
6. To make optional pan-jus gravy, turn off the heat and drain excess oil. While the pan is still hot, add 2.5 tablespoons of water and scrape up the pan drippings with a spoon.
7. Drizzle the pan juices over the rissoles and serve with your preferred sides.
8. Alternatively, preheat an air fryer to 180°C for 3-5 minutes.
9. Lightly spray or brush both sides of the rissoles with olive oil.
10. Place the rissoles in a single layer in the air fryer basket without touching. Cook in batches if needed.
11. Air fry for 10-12 minutes, flipping halfway through. Use regular beef mince rather than lean beef mince to prevent dry rissoles.'
WHERE `id` = 330119
  AND `remote_url` = 'https://simplehomeedit.com/recipe/beef-rissoles/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 660116  Butternut Squash Lasagna
--     https://bellesbestbites.com/ina-garten-butternut-squash-lasagna/
UPDATE `recipe` SET `method` = '1. Preheat the oven to 200°C.
2. Place the butternut squash on a baking sheet, drizzle with olive oil, season with salt and pepper, and toss to coat. Roast for 25-30 minutes until tender and lightly caramelised. Set aside to cool slightly.
3. Combine the ricotta cheese, egg, half the grated parmesan, salt, and pepper in a medium bowl. Stir until smooth, then set aside.
4. Melt the butter in a medium saucepan over medium heat. Whisk in the flour and cook for 1-2 minutes until lightly golden.
5. Gradually whisk in the milk until smooth. Add the nutmeg and sage, then cook for 5-7 minutes, stirring frequently, until thickened.
6. Season the béchamel sauce with salt and pepper, then set aside.
7. Bring a large pot of salted water to the boil. Cook the lasagne sheets according to the packet instructions until al dente, then drain and lay flat to prevent sticking.
8. Preheat the oven to 190°C. Spread a thin layer of béchamel sauce in the bottom of a greased 23 × 33 cm baking dish. Cover with a layer of lasagne sheets.
9. Layer over half the roasted butternut squash, half the ricotta mixture, more béchamel sauce, and mozzarella.
10. Add another layer of lasagne sheets, followed by the remaining squash, ricotta mixture, béchamel sauce, and mozzarella.
11. Finish with a final layer of lasagne sheets and béchamel sauce. Sprinkle with the remaining grated parmesan and mozzarella.
12. Cover with foil and bake for 30 minutes. Remove the foil and bake for a further 15 minutes, until golden and bubbling.
13. Rest the lasagna for 10 minutes before serving.
14. Garnish with parsley, slice, and serve.'
WHERE `id` = 660116
  AND `remote_url` = 'https://bellesbestbites.com/ina-garten-butternut-squash-lasagna/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 720116  Chicken Madras
--     https://mistyricardo.com/madras-recipe/
UPDATE `recipe` SET `method` = '1. Heat the oil in a frying pan over medium-high heat. Add the cassia bark and cumin seeds, then fry for 30-45 seconds, stirring frequently.
2. Add the ginger & garlic paste and stir for about 30 seconds, until it begins to brown and the sizzling reduces.
3. Add the chilli powder, mix powder, kasuri methi, salt and 30 millilitres of base gravy. Stir to cook the spices without burning them.
4. Fry for 20-30 seconds, stirring frequently with the flat of a spoon to distribute the spices evenly.
5. Add the tomato paste. Increase the heat to high and stir frequently until the oil separates and small dry craters appear around the edge of the pan.
6. Add your chosen pre-cooked main ingredient, coriander stalks, lemon dressing or juice and optional coffee granules. Mix well into the sauce.
7. Add 75 millilitres of base gravy. Stir and scrape everything together, then leave to cook without stirring until dry craters form again.
8. Add a further 75 millilitres of base gravy. Stir and scrape the bottom and sides of the pan once, then allow the sauce to reduce again without unnecessary stirring.
9. Add 150 millilitres of base gravy, Worcestershire sauce, optional onion paste and optional mango chutney. Stir and scrape once when first added.
10. Cook over high heat for 4-5 minutes. Stir and scrape any caramelisation back into the sauce only as needed to prevent sticking or burning.
11. Add extra base gravy towards the end of cooking if needed to reach your preferred consistency.
12. Remove the cassia bark and spoon off any excess oil if desired. Serve topped with the coriander leaves.'
WHERE `id` = 720116
  AND `remote_url` = 'https://mistyricardo.com/madras-recipe/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 750117  Base Curry Sauce
--     https://mistyricardo.com/base-gravy-recipe/
UPDATE `recipe` SET `method` = '1. Add the oil to a large pan with a minimum 5 litre capacity and set over medium heat.
2. Add the onion, carrot, green pepper, potato, ginger & garlic paste, and salt. Cook for 5 minutes, stirring frequently.
3. Cover, reduce the heat to very low, and simmer gently for 1 hour, stirring occasionally, until the onion is fully softened and melted in appearance.
4. Increase the heat to medium. Add the mix powder, turmeric, and garam masala, then cook for 1 minute while stirring.
5. Add the tomato puree, coconut block, optional jaggery or brown sugar, and water. Stir well. Coconut milk may be used instead of coconut block.
6. Bring to the boil, cover, reduce the heat to low, and simmer gently for 1 hour, stirring very occasionally.
7. Optionally add the coriander a few minutes before the end of the simmering time.
8. Turn off the heat and allow the gravy to cool slightly.
9. Blend until very smooth, preferably with a stick blender.
10. Bring back to the boil and simmer gently for 25 minutes.
11. Turn off the heat and allow to cool. Stir and blend again if there are any lumps.
12. For use in curries, dilute the base gravy with an equal amount of water to a semi-skimmed milk consistency, then heat before using.
13. Refrigerate or freeze any unused gravy.

Optional pressure-cooker method:
1. After frying the stage 1 vegetables for 5 minutes, seal the pressure cooker and bring to pressure over high heat.
2. Reduce the heat to low and cook under pressure for about 15 minutes. Release the pressure and continue with stage 2.
3. After adding the stage 2 ingredients, repeat the pressure-cooking process. Add optional coriander after releasing the pressure, then simmer for 5 minutes.
4. Complete stage 3 as above.'
WHERE `id` = 750117
  AND `remote_url` = 'https://mistyricardo.com/base-gravy-recipe/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 750118  Chicken Saag
--     https://mistyricardo.com/chicken-saag-curry-recipe/
UPDATE `recipe` SET `method` = '1. Heat oil in a frying pan or wok over medium-high heat.
2. Add the cumin seeds and panch phoran. Stir until the mustard seeds in the spice mix begin to crackle.
3. Add the salt and onion. Fry for a few minutes, stirring occasionally, until softened and browning at the edges.
4. Add the garlic and fry for 1 minute.
5. Add 1 teaspoon of mix powder and fry for 20 seconds, stirring continuously.
6. Add the spinach and cook, stirring frequently, until the excess water has evaporated and it forms a thick reduction. Set aside.
7. Heat oil in a frying pan over medium-high heat for the curry.
8. Add the ginger and garlic paste and fry for about 20 seconds, stirring continuously, until it changes colour and begins to crackle.
9. Add 1 teaspoon of mix powder, salt, chilli powder, kasuri methi, and a splash of base gravy. Fry for 20-30 seconds, stirring continuously.
10. Stir in the tomato paste and coriander stalks. Increase the heat to high and fry for a further 20 seconds, stirring often.
11. Add the chicken and 75 millilitres of base gravy. Mix well to coat.
12. Add another 75 millilitres of base gravy, stir once, and let the sauce reduce until oil surfaces and small craters appear.
13. Add a further 75 millilitres of base gravy. Stir and scrape the bottom and sides of the pan when first added, then allow the sauce to reduce again.
14. Add the prepared spinach and mix well.
15. Add 150 millilitres of base gravy, the mango powder or lemon juice, and mint. Mix well, scraping the bottom and sides of the pan, then cook over high heat for 4-5 minutes. Stir and scrape a few times to prevent burning while allowing the sauce to thicken and caramelise.
16. Add the tomato segments shortly before serving. Stir in butter ghee if using.
17. Taste and adjust with extra salt, lemon juice, or mint sauce if desired.
18. Serve topped with fresh coriander leaves.'
WHERE `id` = 750118
  AND `remote_url` = 'https://mistyricardo.com/chicken-saag-curry-recipe/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 840116  Butter Chicken (base gravy)
--     https://mistyricardo.com/butter-chicken-recipe/
UPDATE `recipe` SET `method` = '1. Heat a frying pan over medium-high heat and add the oil or ghee.
2. Once hot, add the cassia bark, cardamom pods, cloves and optional fennel seeds. Fry for 30-40 seconds, stirring frequently, to infuse the oil.
3. Add the onion and fry for a couple of minutes, stirring occasionally, until translucent and beginning to brown.
4. Add the ginger & garlic paste and cook for 15-30 seconds, stirring frequently, until the sizzling subsides.
5. Add the mix powder, tandoori masala, garam masala, paprika, kasuri methi and optional kashmiri chilli powder. Fry for 20-30 seconds, stirring very frequently. Add a little base gravy if the mixture becomes dry.
6. Add the tomato paste. Turn the heat to high and stir constantly until the oil separates and small craters appear.
7. Add the chicken and coat well in the sauce.
8. Stir in the lemon juice.
9. Add 75 millilitre base gravy. Stir it into the sauce, then leave on high heat without further stirring until slightly reduced, the oil separates and craters form around the edges.
10. Add another 75 millilitre base gravy, stirring and scraping the bottom and sides of the pan once when first added. Allow the sauce to reduce again.
11. Add the remaining 100 millilitre base gravy, stir and scrape the pan, then cook for 4-5 minutes. Stir and scrape once or twice to prevent sticking, allowing some sauce to caramelise on the bottom and sides of the pan. Add extra base gravy if the sauce becomes too thick.
12. One minute before the end of cooking, reduce the heat to low. Add the single cream, jaggery or brown sugar, and unsalted butter or ghee. Stir until melted.
13. Remove and discard the cassia bark, cloves and cardamom pods.
14. Serve garnished with fresh coriander.'
WHERE `id` = 840116
  AND `remote_url` = 'https://mistyricardo.com/butter-chicken-recipe/'
  AND (`method` IS NULL OR TRIM(`method`) = '');

-- 840117  Lamb Rogan Josh
--     https://mistyricardo.com/rogan-josh-curry-recipe/
UPDATE `recipe` SET `method` = '1. Heat a frying pan over medium-high heat and add the oil.
2. Add the cassia bark, fennel seeds, black cardamom seeds, and optional bay leaf. Fry for 30-45 seconds, stirring frequently.
3. Add the onion and red pepper. Fry for a couple of minutes until slightly softened, stirring occasionally.
4. Add the ginger and garlic paste and cook for 15-30 seconds, stirring frequently, until the sizzling subsides.
5. Add the toasted ground cumin and coriander seeds, mix powder, Kashmiri chilli powder, salt, black pepper, tandoori masala, paprika, and kasuri methi.
6. Fry for 20-30 seconds, stirring very frequently. Add a little base gravy if the mixture becomes dry.
7. Add the tomato paste. Increase the heat to high and stir constantly until the oil separates and small craters appear.
8. Add the coriander stalks and pre-cooked lamb or other chosen protein. Coat in the sauce.
9. Add 75 millilitres base gravy, stir, then leave over high heat without further stirring until slightly reduced and craters form at the edges.
10. Add another 75 millilitres base gravy, stirring and scraping the base and sides of the pan once, then allow the sauce to reduce again.
11. Add the final 150 millilitres base gravy. Stir and scrape the pan, then cook over high heat for 4-5 minutes until medium consistency. Stir only once or twice to prevent sticking or burning.
12. About 1 minute before cooking is complete, reduce the heat to low and stir in the natural yoghurt.
13. Remove and discard the cassia bark and bay leaf. Transfer the curry to a warm serving dish, leaving any residue in the pan.
14. Return the pan to medium-high heat and add the ghee. Once melted, add the tomatoes, coriander leaves, garam masala, and about 40 millilitres base gravy. Stir and allow the sauce to caramelise.
15. Add a little water to loosen the sauce and deglaze the pan, scraping in the sticky residue.
16. After 2-3 minutes, once the tomatoes have softened, pour the topping over the curry and serve.'
WHERE `id` = 840117
  AND `remote_url` = 'https://mistyricardo.com/rogan-josh-curry-recipe/'
  AND (`method` IS NULL OR TRIM(`method`) = '');


-- 136 of 157 Recipes had no method.
-- 56 were backfilled above.
-- 12 were re-read and could not be used:
--   12  Sausage, Pea and Potato Casserole - No ingredients could be read from that page. Try another link, or use Enter Manually.
--   38  Baked Nduja Rigatoni - No ingredients could be read from that page. Try another link, or use Enter Manually.
--   39  Mushroom Ravioli - No ingredients could be read from that page. Try another link, or use Enter Manually.
--   40  Chicken katsu curry - No ingredients could be read from that page. Try another link, or use Enter Manually.
--   42  Lasagne (Dairy Free) - No ingredients could be read from that page. Try another link, or use Enter Manually.
--   52  Yorkshire Puddings - the page was read but carries no method
--   54  Korean Fried Chicken w/ Slaw - No ingredients could be read from that page. Try another link, or use Enter Manually.
--   69  Pork Casserole - No ingredients could be read from that page. Try another link, or use Enter Manually.
--   70  Kung Pao Chicken - No ingredients could be read from that page. Try another link, or use Enter Manually.
--   72  Egg Fried Rice - No ingredients could be read from that page. Try another link, or use Enter Manually.
--   82  Akuri (Breakfast) - No ingredients could be read from that page. Try another link, or use Enter Manually.
--   102  Sri Lankan Veg Hash - No ingredients could be read from that page. Try another link, or use Enter Manually.
-- 68 have no URL to re-read, and no source but the cook:
--   28  Almond Chicken (migdałowe)
--   570117  Baked Beans in Spicy Tomato Sauce
--   88  Beef Stir Fry
--   90135  Berries galore overnight oats
--   108  Black Daal
--   87  Brisket Tacos
--   180117  Buckwheat and Beetroot salad
--   90144  Burrito bowl
--   90140  Butterbean and vegetable soup
--   111  Carribean Vegan Jerk Chilli
--   93  Chamonix Salad
--   90129  Chia, carrot and pecan oats
--   23  Chicken and Chorizo Salad
--   210116  Chicken and vegetable stir-fry with noodles
--   19  Chicken Korma
--   4  Chilli Con Carne
--   90139  Courgette fritters and salsa verde
--   390116  Curried Cauliflower & Potato Pasties
--   16  Duck with Cabbage
--   113  Fajitas with mixed mushrooms
--   18  Fish Cakes
--   7  Fish Pie
--   29  French Macarons
--   60  Green Bean and Bacon Salad
--   86  Gunpowder Potatoes
--   180116  Jewelled quinoa
--   90130  Kale omlette
--   115  Keema-Spiced Shepherds Pie
--   5  Kotlety
--   14  Lamb Bhuna
--   85  Lamb Chops (dishoom)
--   98  Lamb Hotpot
--   84  Lamb Samosas
--   240118  Masala Prawns
--   63  Mushroom Strogranoff
--   120118  One Pot Smoky Cod
--   570119  Pan Con Tomate
--   22  Pan Fried Salmon
--   90118  Pancakes
--   61  Passion Fruit Pavlova
--   17  Pea and Pancetta Pasta
--   3  Pea and Pancetta Risotto
--   90136  Poached pear porridge
--   8  Pork and Chorizo Burgers
--   59  Pork Fillet with Cabbage
--   31  Prawn French Toast
--   90142  Prawn poke bowl
--   27  Rack of Lamb
--   11  Roast Beef
--   34  Roast Glazed Ham
--   65  Rosoł
--   240119  Saag Paneer
--   90137  Salmon and asparagus frittata
--   90141  Salmon with harissa vegetable couscous
--   90143  Salmon with Puy lentils
--   6  Sausage and Mash
--   90132  Scrambled eggs with garlic mushrooms and asparagus
--   630116  Sea bass with roasted vegetables
--   30  Seared Pork Chops With Mushrooms
--   37  Singapore Laksa
--   62  Sirloin Steak with Broccoli
--   32  Smartie Cookies
--   2  Spaghetti Bolognese
--   90145  Sweet potato cottage pie
--   58  Sweet Potato Curry
--   420116  The Ultimate Sausage Roll
--   90131  Watermelon and strawberry smoothie
--   570116  White bean stew with chorizo and black pudding

-- Verification - expect no rows:
-- SELECT id, name FROM `recipe` WHERE id IN (1, 10, 13, 15, 20, 21, 24, 25, 26, 33, 36, 41, 43, 44, 45, 49, 50, 51, 55, 56, 57, 64, 66, 67, 68, 83, 89, 94, 99, 100, 101, 106, 107, 109, 112, 114, 90116, 90117, 150116, 240120, 270116, 300116, 300117, 300118, 300119, 300120, 330116, 330117, 330118, 330119, 660116, 720116, 750117, 750118, 840116, 840117)
--   AND (method IS NULL OR TRIM(method) = '');
