package app

import (
	"context"
	"errors"
	"net/http"
	"time"

	"recipes/internal/pkg/service"
	"recipes/internal/pkg/service/email"

	"github.com/danielgtaylor/huma/v2"
)

// The two routes behind account linking recovery - see
// specs/account-linking-recovery.md and the header of service/link.go.
//
// Somebody whose second provider handed over a different verified address gets
// a brand new, empty Account and no error anywhere, because at the level of the
// data there is nothing wrong. These let them prove they own the other account
// the only way that actually proves it: by signing into it.

// LinkStartInput is the body of POST /link/start.
//
// **It cannot name a subject, and that is the point of the type.** The identity
// being granted access is always `caller.Subject`, lifted from the validated
// token - a field here would let a caller start a link that hands some
// stranger's login their own account, spelled entirely in public values. This is
// CreateUserInput's rule (no Email field) applied to the other half of the same
// design.
type LinkStartInput struct {
	Body struct {
		// Nonce is generated by the browser and kept in its own localStorage.
		// The server stores only a digest; see service.CompleteLink for why this
		// is what makes the grant non-transferable.
		//
		// Bounded at both ends. The minimum is not a strength check - the server
		// cannot tell a random 32 bytes from a typed word - but it refuses the
		// obviously empty, and the maximum stops an arbitrarily long body being
		// hashed and stored.
		Nonce string `json:"nonce" minLength:"16" maxLength:"256" doc:"A random value held in the calling browser's own storage."`
	}
}

// LinkStartOutput hands back the token and names the sign-in method being
// linked.
type LinkStartOutput struct {
	Body struct {
		// Token redeems this link request at POST /link/complete. Useless on its
		// own: completing also needs the nonce, which never leaves the browser
		// that generated it.
		Token string `json:"token"`
		// Provider is the human name of the identity provider the caller is
		// currently signed in with - "Apple", "Google" - or "" when it is not
		// one we recognise.
		//
		// Sent so the confirmation screen can say *which* sign-in is about to be
		// given access, in a sentence the person is being asked to make a
		// security decision about. It is returned here rather than at completion
		// because by then the caller has re-authenticated as somebody else and
		// the browser is the only thing that still knows.
		//
		// **The subject itself is deliberately not returned.** It is a stable
		// identifier for a person at their identity provider, and ADR-0008 keeps
		// those out of anything user-facing.
		Provider string `json:"provider"`
	}
}

// LinkCompleteInput is the body of POST /link/complete.
type LinkCompleteInput struct {
	Body struct {
		Token string `json:"token" minLength:"1" maxLength:"128" doc:"The token POST /link/start returned."`
		Nonce string `json:"nonce" minLength:"16" maxLength:"256" doc:"The nonce the same browser generated when it started this link."`
	}
}

// LinkCompleteOutput confirms what now reaches this Account.
type LinkCompleteOutput struct {
	Body struct {
		// Provider names the sign-in method that was added, so the confirmation
		// can be specific without the client having had to remember anything.
		Provider string `json:"provider"`
	}
}

// startLink issues a token for the caller's current sign-in.
//
// It writes nothing that grants anything: the row says "this subject is asking
// to be let in somewhere" and names no target at all. Whoever lets it in is
// decided at completion, by whoever re-authenticates - which is why this being
// cheap and authenticated is enough, and why the closed question about rate
// limiting could be answered "not now": the worst an authenticated caller
// achieves by hammering it is issuing tokens bound to their own subject, and
// those do nothing without the nonce and a successful re-authentication.
func (a *App) startLink(ctx context.Context, input *LinkStartInput) (*LinkStartOutput, error) {
	caller := callerFrom(ctx)

	token, err := service.StartLink(ctx, a.db, caller.Subject, input.Body.Nonce)
	if err != nil {
		return nil, fail(ctx, huma.Error500InternalServerError("could not start the link"), err)
	}

	out := &LinkStartOutput{}
	out.Body.Token = token
	out.Body.Provider = service.ProviderName(caller.Subject)
	return out, nil
}

// completeLink redeems a started link.
//
// The caller has, by this point, been sent back through Auth0 with
// `prompt=login` and signed in as the account they are claiming. That
// re-authentication is the proof of ownership; the nonce in the body is the
// proof that the browser finishing the link is the one that started it. Neither
// is sufficient alone - see service.CompleteLink.
func (a *App) completeLink(ctx context.Context, input *LinkCompleteInput) (*LinkCompleteOutput, error) {
	caller := callerFrom(ctx)

	outcome, err := service.CompleteLink(ctx, a.db, caller.Subject, input.Body.Token, input.Body.Nonce)
	if err != nil {
		// A refusal is something the person can act on; anything else is our
		// data or our database in a state it should not be in, which is a 500
		// and not theirs to read about. Both go through fail(), so the real
		// cause reaches the span either way - see register.go.
		if refusal := linkRefusal(err); refusal != nil {
			return nil, fail(ctx, refusal, err)
		}
		return nil, fail(ctx, huma.Error500InternalServerError("could not link the accounts"), err)
	}

	// **The only thing that tells the account's owner this happened.**
	//
	// Everything else in this design makes the grant hard to obtain - the
	// re-authentication, the nonce, the single-use token. None of it lets the
	// owner *find out*: a successful trick, or an honest mistake, adds a
	// permanent new way into an account and says nothing to anybody outside
	// that browser session.
	//
	// **It is the one place SendGrid belongs in this feature, because it
	// carries no grant.** No link, no token, nothing to act on - so phishing a
	// copy of it achieves nothing. That is exactly what the emailed
	// confirmation link this spec rejects was not.
	//
	// Best-effort and asynchronous like every other transactional send, and
	// here that is load-bearing rather than conventional: the link has already
	// happened and been committed by the time this runs, so a send failure has
	// nothing to undo and must not be allowed to report one.
	// SendTransactionalAsync returns nothing, which is what makes that
	// impossible rather than merely intended.
	//
	// An empty address is not a failure - migrations/044 normalises blanks to
	// NULL and a user can legitimately have none on file. The email package
	// treats a recipient with no address as the unconfigured case and stays
	// quiet.
	email.SendTransactionalAsync(ctx,
		email.Recipient{Name: outcome.Name, Address: outcome.Email},
		email.KindSignInAdded,
		email.SignInAddedData{
			Name:     outcome.Name,
			Provider: outcome.Provider,
			// UTC, with the zone named. See the field's comment for why this is
			// not the recipient's local time.
			When: time.Now().UTC().Format("2 January 2006 at 15:04 MST"),
		})

	out := &LinkCompleteOutput{}
	out.Body.Provider = outcome.Provider
	return out, nil
}

// linkRefusal turns a refusal from the service layer into what the person reads,
// or nil for an error that is not a refusal at all.
//
// **nil rather than a 500 of its own**, so that the one place a 5xx is built in
// this file is the handler, on a line that also calls fail(). That is not a
// style preference: TestNoHandlerSwallowsTheCauseOfA500 reads this package's
// source for exactly that shape, after a day in production where every Recipe
// answered 500 and the cause ("Unknown column 'featured'") reached neither the
// logs nor the trace.
//
// A table rather than a chain of ifs at the call site because each of these is a
// different piece of advice, and the differences are the feature: "that has
// expired" and "you already have recipes here" want completely different next
// actions from the reader.
//
// **The messages are written for somebody who is confused and slightly
// alarmed**, which is the state anybody reaching this flow is in - they have
// just found an empty account where their recipes should be. None of them names
// a provider, an address or another account, for the same reason the spec's
// accepted weaknesses say we cannot tell them which provider they signed up
// with: answering would turn these routes into an account-enumeration oracle.
func linkRefusal(err error) error {
	switch {
	// One message for "never issued", "already redeemed" and "purged", because
	// the service layer deliberately does not distinguish them - saying which
	// would confirm whether a token somebody is guessing at ever existed.
	case errors.Is(err, service.ErrLinkUnknown):
		return huma.Error400BadRequest(
			"That link request is no longer valid. Start again from the shopping list.")
	case errors.Is(err, service.ErrLinkExpired):
		return huma.Error400BadRequest(
			"That link request has expired. Start again from the shopping list and finish signing in within a few minutes.")
	// Not spelled out as "your browser did not have the right nonce", which
	// tells an attacker exactly what they are missing and tells everybody else
	// nothing. The honest version for the person who hits it legitimately -
	// they finished in a different browser - is also the more useful one.
	case errors.Is(err, service.ErrLinkNonceMismatch):
		return huma.Error400BadRequest(
			"This has to be finished in the same browser you started it in. Start again there.")
	case errors.Is(err, service.ErrLinkSameIdentity):
		return huma.Error409Conflict(
			"You signed in with the same method you are already using, so there is nothing to link. Try again and choose the one you used originally.")
	case errors.Is(err, service.ErrLinkAlreadyLinked):
		return huma.Error409Conflict(
			"Those two ways of signing in already reach the same account.")
	// The one refusal with no self-service remedy, so it is the one that names
	// support. Merging two populated accounts is a much larger problem -
	// duplicate recipes, two shopping lists, two sets of invites - and is
	// deliberately out of scope.
	case errors.Is(err, service.ErrLinkSourceHasRecipes):
		return huma.Error409Conflict(
			"This account already has recipes in it, so it cannot be merged with another one automatically. Please contact support and we will help.")
	}
	// Not a refusal. The caller decides what to do with it, and there is
	// exactly one thing it can be.
	return nil
}

func (a *App) registerLinkRoutes(api huma.API) {
	register(api, huma.Operation{
		OperationID: "start-link",
		Method:      http.MethodPost,
		Path:        "/link/start",
		Summary:     "Start linking the current sign-in to an existing account",
		Description: "Issues a short-lived, single-use token bound to the caller's own Auth0 subject. " +
			"Grants nothing on its own: redeeming it also needs the nonce, which stays in the calling " +
			"browser's storage, and a successful re-authentication as the account being linked to.",
		Tags: []string{"Account"},
	}, a.startLink)

	register(api, huma.Operation{
		OperationID: "complete-link",
		Method:      http.MethodPost,
		Path:        "/link/complete",
		Summary:     "Finish linking a sign-in to the caller's account",
		Description: "Grants the subject the token names access to the Account the caller is signed into, " +
			"and erases the empty Account that subject used to reach. Refused if that Account holds any recipes.",
		Tags: []string{"Account"},
	}, a.completeLink)
}
